/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Location } from './location';

/**
 * 
 * @export
 * @interface CreateShiftRequest
 */
export interface CreateShiftRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateShiftRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateShiftRequest
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof CreateShiftRequest
     */
    'company': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateShiftRequest
     */
    'tags': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateShiftRequest
     */
    'startTime': string;
    /**
     * 
     * @type {string}
     * @memberof CreateShiftRequest
     */
    'endTime': string;
    /**
     * 
     * @type {number}
     * @memberof CreateShiftRequest
     */
    'pay': number;
    /**
     * 
     * @type {Location}
     * @memberof CreateShiftRequest
     */
    'location': Location;
}

