/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompanyDto } from './company-dto';

/**
 * 
 * @export
 * @interface GetRequestingUserCompany200Response
 */
export interface GetRequestingUserCompany200Response {
    /**
     * 
     * @type {string}
     * @memberof GetRequestingUserCompany200Response
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof GetRequestingUserCompany200Response
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof GetRequestingUserCompany200Response
     */
    'owner': string;
}

